FROM docker.io/library/alpine:3.20

RUN echo "Official container ready"

RUN apk add --no-cache wget

WORKDIR /shared

CMD ["sh", "-c", "\
    wget https://registry.npmjs.org/svelte/-/svelte-5.48.2.tgz -O official.tgz && \
    echo Official package downloaded"]
