FROM node:25-alpine

RUN echo "Builder container ready"

RUN set -x
RUN apk update && apk upgrade --no-cache
RUN apk add --no-cache git pnpm

WORKDIR /app

RUN git clone --depth 1 https://github.com/sveltejs/svelte.git .
# Since tags can be moved, we fetch the specific commit instead.
RUN git fetch --depth 1 origin e1427aa0c8b5abe88aea972ea397ea499cb8f2db
RUN git checkout e1427aa0c8b5abe88aea972ea397ea499cb8f2db
RUN pnpm install --frozen-lockfile
RUN pnpm build --filter ./packages/svelte
RUN mkdir /shared
RUN cd packages/svelte && pnpm pack --pack-destination /shared

CMD ["sh", "-c", "echo Builder package created"]
