FROM docker.io/library/node:25-alpine

RUN apk add --no-cache git pnpm diffoscope wget

WORKDIR /app

# Since tags can be moved, we fetch the specific commit instead.
RUN git clone https://github.com/sveltejs/svelte.git .
RUN git fetch --depth 1 origin e1427aa0c8b5abe88aea972ea397ea499cb8f2db
RUN git checkout e1427aa0c8b5abe88aea972ea397ea499cb8f2db

RUN pnpm install --frozen-lockfile
RUN pnpm build --filter ./packages/svelte

# pnpm pack generate tgz file
RUN cd packages/svelte && pnpm pack --pack-destination /tmp

# Testing diffoscope works
# RUN printf '\n' >> /tmp/svelte-5.48.2.tgz

# Compare
CMD sh -c "\
    set -x && \
    wget https://registry.npmjs.org/svelte/-/svelte-5.48.2.tgz -O /tmp/official.tgz && \
    ls -lah /tmp && \
    diffoscope /tmp/svelte-5.48.2.tgz /tmp/official.tgz"
